name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
         os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Build
      run: ./gradlew build -PRunToolchainTests
    - name: Publish
      run: ./gradlew publishToMavenLocal
    - name: Check output
      run: git --no-pager diff --exit-code HEAD

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Publish to Maven Local
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew publishToMavenLocal
      - name: Publish to PhotonVision Maven
        if: ${{ github.repository_owner == 'photonvision' && startsWith(github.ref, 'refs/tags/v') }}
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: ./gradlew publish -x publishPluginMavenPublicationToMavenLocal
